spring:
  mail:
    host: smtp.gmail.com
    username: fadwacherqui2@gmail.com
    password: "djqfvhlocrsrfnuy"  # Remove spaces from the password
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
