spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aftas
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include-message: always